version: "3"
services:
  web:
    build: .
    working_dir: /home/node/gotchin
    environment:
      - HOST=0.0.0.0
    volumes:
      - ./:/home/node/gotchin
    restart: always
    ports:
      - "3000:3000"
    command: yarn dev
